# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'input.ui'
#
# Created: Sat Jun 23 10:26:17 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_InputDialog(object):
    def setupUi(self, InputDialog):
        InputDialog.setObjectName(_fromUtf8("InputDialog"))
        InputDialog.resize(858, 654)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(InputDialog.sizePolicy().hasHeightForWidth())
        InputDialog.setSizePolicy(sizePolicy)
        InputDialog.setMinimumSize(QtCore.QSize(858, 654))
        InputDialog.setWindowTitle(_fromUtf8("Mupen64Plus SDL Input Plugin"))
        InputDialog.setToolTip(_fromUtf8(""))
        self.verticalLayout_8 = QtGui.QVBoxLayout(InputDialog)
        self.verticalLayout_8.setMargin(10)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.groupBox = QtGui.QGroupBox(InputDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setStyleSheet(_fromUtf8("QGroupBox {\n"
"    border: 1px solid #7F7F7F;\n"
"    border-radius: 3px;\n"
"    margin-top: 1ex; \n"
" }\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left; \n"
"    padding: 0 2px;\n"
" }"))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_6.setMargin(10)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.comboController = QtGui.QComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboController.sizePolicy().hasHeightForWidth())
        self.comboController.setSizePolicy(sizePolicy)
        self.comboController.setObjectName(_fromUtf8("comboController"))
        self.horizontalLayout_4.addWidget(self.comboController)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.checkPlugged = QtGui.QCheckBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkPlugged.sizePolicy().hasHeightForWidth())
        self.checkPlugged.setSizePolicy(sizePolicy)
        self.checkPlugged.setObjectName(_fromUtf8("checkPlugged"))
        self.gridLayout.addWidget(self.checkPlugged, 0, 0, 1, 1)
        self.checkMouse = QtGui.QCheckBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkMouse.sizePolicy().hasHeightForWidth())
        self.checkMouse.setSizePolicy(sizePolicy)
        self.checkMouse.setObjectName(_fromUtf8("checkMouse"))
        self.gridLayout.addWidget(self.checkMouse, 1, 0, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout)
        self.gridLayout_7.addWidget(self.groupBox_4, 0, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.comboPlugin = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboPlugin.sizePolicy().hasHeightForWidth())
        self.comboPlugin.setSizePolicy(sizePolicy)
        self.comboPlugin.setObjectName(_fromUtf8("comboPlugin"))
        self.gridLayout_2.addWidget(self.comboPlugin, 0, 2, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.comboDevice = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboDevice.sizePolicy().hasHeightForWidth())
        self.comboDevice.setSizePolicy(sizePolicy)
        self.comboDevice.setObjectName(_fromUtf8("comboDevice"))
        self.gridLayout_2.addWidget(self.comboDevice, 1, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 1, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_2)
        self.gridLayout_7.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_28.addWidget(self.label_3)
        spacerItem3 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem3)
        self.label_13 = QtGui.QLabel(self.groupBox_3)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_28.addWidget(self.label_13)
        self.spinDeadzoneX = QtGui.QSpinBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinDeadzoneX.sizePolicy().hasHeightForWidth())
        self.spinDeadzoneX.setSizePolicy(sizePolicy)
        self.spinDeadzoneX.setMaximum(65535)
        self.spinDeadzoneX.setObjectName(_fromUtf8("spinDeadzoneX"))
        self.horizontalLayout_28.addWidget(self.spinDeadzoneX)
        self.label_14 = QtGui.QLabel(self.groupBox_3)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_28.addWidget(self.label_14)
        self.spinDeadzoneY = QtGui.QSpinBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinDeadzoneY.sizePolicy().hasHeightForWidth())
        self.spinDeadzoneY.setSizePolicy(sizePolicy)
        self.spinDeadzoneY.setMaximum(65535)
        self.spinDeadzoneY.setObjectName(_fromUtf8("spinDeadzoneY"))
        self.horizontalLayout_28.addWidget(self.spinDeadzoneY)
        self.verticalLayout_14.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_25.addWidget(self.label_4)
        spacerItem4 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem4)
        self.label_15 = QtGui.QLabel(self.groupBox_3)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_25.addWidget(self.label_15)
        self.spinPeakX = QtGui.QSpinBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinPeakX.sizePolicy().hasHeightForWidth())
        self.spinPeakX.setSizePolicy(sizePolicy)
        self.spinPeakX.setMaximum(65535)
        self.spinPeakX.setObjectName(_fromUtf8("spinPeakX"))
        self.horizontalLayout_25.addWidget(self.spinPeakX)
        self.label_16 = QtGui.QLabel(self.groupBox_3)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_25.addWidget(self.label_16)
        self.spinPeakY = QtGui.QSpinBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinPeakY.sizePolicy().hasHeightForWidth())
        self.spinPeakY.setSizePolicy(sizePolicy)
        self.spinPeakY.setMaximum(65535)
        self.spinPeakY.setObjectName(_fromUtf8("spinPeakY"))
        self.horizontalLayout_25.addWidget(self.spinPeakY)
        self.verticalLayout_14.addLayout(self.horizontalLayout_25)
        self.gridLayout_7.addWidget(self.groupBox_3, 0, 2, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_7)
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_6.setTitle(_fromUtf8(""))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_5.setMargin(10)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        spacerItem5 = QtGui.QSpacerItem(168, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem5, 0, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.pushL_Trig = InputButton(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pushL_Trig.sizePolicy().hasHeightForWidth())
        self.pushL_Trig.setSizePolicy(sizePolicy)
        self.pushL_Trig.setMinimumSize(QtCore.QSize(0, 0))
        self.pushL_Trig.setAutoDefault(False)
        self.pushL_Trig.setObjectName(_fromUtf8("pushL_Trig"))
        self.horizontalLayout_5.addWidget(self.pushL_Trig)
        self.label_12 = QtGui.QLabel(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_5.addWidget(self.label_12)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_5)
        spacerItem6 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_11 = QtGui.QLabel(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_6.addWidget(self.label_11)
        self.pushR_Trig = InputButton(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pushR_Trig.sizePolicy().hasHeightForWidth())
        self.pushR_Trig.setSizePolicy(sizePolicy)
        self.pushR_Trig.setAutoDefault(False)
        self.pushR_Trig.setObjectName(_fromUtf8("pushR_Trig"))
        self.horizontalLayout_6.addWidget(self.pushR_Trig)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)
        self.gridLayout_8.addLayout(self.horizontalLayout_7, 0, 1, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(178, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem7, 0, 2, 1, 1)
        self.groupBox_8 = QtGui.QGroupBox(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_8.sizePolicy().hasHeightForWidth())
        self.groupBox_8.setSizePolicy(sizePolicy)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_8)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_26 = QtGui.QLabel(self.groupBox_8)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_3.addWidget(self.label_26, 0, 0, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem8, 0, 1, 1, 1)
        self.pushDPad_U = InputButton(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushDPad_U.sizePolicy().hasHeightForWidth())
        self.pushDPad_U.setSizePolicy(sizePolicy)
        self.pushDPad_U.setAutoDefault(False)
        self.pushDPad_U.setObjectName(_fromUtf8("pushDPad_U"))
        self.gridLayout_3.addWidget(self.pushDPad_U, 0, 2, 1, 1)
        self.label_25 = QtGui.QLabel(self.groupBox_8)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_3.addWidget(self.label_25, 1, 0, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem9, 1, 1, 1, 1)
        self.pushDPad_D = InputButton(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushDPad_D.sizePolicy().hasHeightForWidth())
        self.pushDPad_D.setSizePolicy(sizePolicy)
        self.pushDPad_D.setAutoDefault(False)
        self.pushDPad_D.setObjectName(_fromUtf8("pushDPad_D"))
        self.gridLayout_3.addWidget(self.pushDPad_D, 1, 2, 1, 1)
        self.label_28 = QtGui.QLabel(self.groupBox_8)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_3.addWidget(self.label_28, 2, 0, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem10, 2, 1, 1, 1)
        self.pushDPad_L = InputButton(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushDPad_L.sizePolicy().hasHeightForWidth())
        self.pushDPad_L.setSizePolicy(sizePolicy)
        self.pushDPad_L.setAutoDefault(False)
        self.pushDPad_L.setObjectName(_fromUtf8("pushDPad_L"))
        self.gridLayout_3.addWidget(self.pushDPad_L, 2, 2, 1, 1)
        self.label_27 = QtGui.QLabel(self.groupBox_8)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_3.addWidget(self.label_27, 3, 0, 1, 1)
        self.pushDPad_R = InputButton(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushDPad_R.sizePolicy().hasHeightForWidth())
        self.pushDPad_R.setSizePolicy(sizePolicy)
        self.pushDPad_R.setAutoDefault(False)
        self.pushDPad_R.setObjectName(_fromUtf8("pushDPad_R"))
        self.gridLayout_3.addWidget(self.pushDPad_R, 3, 2, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem11, 3, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.gridLayout_8.addWidget(self.groupBox_8, 1, 0, 1, 1)
        self.labelImage = QtGui.QLabel(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.labelImage.sizePolicy().hasHeightForWidth())
        self.labelImage.setSizePolicy(sizePolicy)
        self.labelImage.setMinimumSize(QtCore.QSize(360, 318))
        self.labelImage.setStyleSheet(_fromUtf8("QLabel {\n"
"    border: 1px solid #7F7F7F;\n"
"    border-radius: 3px;\n"
"    margin-top: 1ex; \n"
" }"))
        self.labelImage.setText(_fromUtf8(""))
        self.labelImage.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/controller.png")))
        self.labelImage.setScaledContents(True)
        self.labelImage.setAlignment(QtCore.Qt.AlignCenter)
        self.labelImage.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.labelImage.setObjectName(_fromUtf8("labelImage"))
        self.gridLayout_8.addWidget(self.labelImage, 1, 1, 2, 1)
        self.groupBox_9 = QtGui.QGroupBox(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_9.sizePolicy().hasHeightForWidth())
        self.groupBox_9.setSizePolicy(sizePolicy)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.pushC_Button_U = InputButton(self.groupBox_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushC_Button_U.sizePolicy().hasHeightForWidth())
        self.pushC_Button_U.setSizePolicy(sizePolicy)
        self.pushC_Button_U.setAutoDefault(False)
        self.pushC_Button_U.setObjectName(_fromUtf8("pushC_Button_U"))
        self.gridLayout_5.addWidget(self.pushC_Button_U, 0, 2, 1, 1)
        self.label_47 = QtGui.QLabel(self.groupBox_9)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.gridLayout_5.addWidget(self.label_47, 2, 0, 1, 1)
        self.pushC_Button_R = InputButton(self.groupBox_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushC_Button_R.sizePolicy().hasHeightForWidth())
        self.pushC_Button_R.setSizePolicy(sizePolicy)
        self.pushC_Button_R.setAutoDefault(False)
        self.pushC_Button_R.setObjectName(_fromUtf8("pushC_Button_R"))
        self.gridLayout_5.addWidget(self.pushC_Button_R, 3, 2, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem12, 0, 1, 1, 1)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem13, 1, 1, 1, 1)
        self.pushC_Button_L = InputButton(self.groupBox_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushC_Button_L.sizePolicy().hasHeightForWidth())
        self.pushC_Button_L.setSizePolicy(sizePolicy)
        self.pushC_Button_L.setAutoDefault(False)
        self.pushC_Button_L.setObjectName(_fromUtf8("pushC_Button_L"))
        self.gridLayout_5.addWidget(self.pushC_Button_L, 2, 2, 1, 1)
        self.label_48 = QtGui.QLabel(self.groupBox_9)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.gridLayout_5.addWidget(self.label_48, 3, 0, 1, 1)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem14, 3, 1, 1, 1)
        self.label_45 = QtGui.QLabel(self.groupBox_9)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout_5.addWidget(self.label_45, 0, 0, 1, 1)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem15, 2, 1, 1, 1)
        self.pushC_Button_D = InputButton(self.groupBox_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushC_Button_D.sizePolicy().hasHeightForWidth())
        self.pushC_Button_D.setSizePolicy(sizePolicy)
        self.pushC_Button_D.setAutoDefault(False)
        self.pushC_Button_D.setObjectName(_fromUtf8("pushC_Button_D"))
        self.gridLayout_5.addWidget(self.pushC_Button_D, 1, 2, 1, 1)
        self.label_46 = QtGui.QLabel(self.groupBox_9)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.gridLayout_5.addWidget(self.label_46, 1, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_5)
        self.gridLayout_8.addWidget(self.groupBox_9, 1, 2, 1, 1)
        self.groupBox_10 = QtGui.QGroupBox(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_10.sizePolicy().hasHeightForWidth())
        self.groupBox_10.setSizePolicy(sizePolicy)
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_50 = QtGui.QLabel(self.groupBox_10)
        self.label_50.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.gridLayout_4.addWidget(self.label_50, 0, 0, 1, 1)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem16, 0, 1, 1, 1)
        self.pushY_Axis_U = InputButton(self.groupBox_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushY_Axis_U.sizePolicy().hasHeightForWidth())
        self.pushY_Axis_U.setSizePolicy(sizePolicy)
        self.pushY_Axis_U.setAutoDefault(False)
        self.pushY_Axis_U.setObjectName(_fromUtf8("pushY_Axis_U"))
        self.gridLayout_4.addWidget(self.pushY_Axis_U, 0, 2, 1, 1)
        self.label_51 = QtGui.QLabel(self.groupBox_10)
        self.label_51.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.gridLayout_4.addWidget(self.label_51, 1, 0, 1, 1)
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem17, 1, 1, 1, 1)
        self.pushY_Axis_D = InputButton(self.groupBox_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushY_Axis_D.sizePolicy().hasHeightForWidth())
        self.pushY_Axis_D.setSizePolicy(sizePolicy)
        self.pushY_Axis_D.setAutoDefault(False)
        self.pushY_Axis_D.setObjectName(_fromUtf8("pushY_Axis_D"))
        self.gridLayout_4.addWidget(self.pushY_Axis_D, 1, 2, 1, 1)
        self.label_49 = QtGui.QLabel(self.groupBox_10)
        self.label_49.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.gridLayout_4.addWidget(self.label_49, 2, 0, 1, 1)
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem18, 2, 1, 1, 1)
        self.pushX_Axis_L = InputButton(self.groupBox_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushX_Axis_L.sizePolicy().hasHeightForWidth())
        self.pushX_Axis_L.setSizePolicy(sizePolicy)
        self.pushX_Axis_L.setAutoDefault(False)
        self.pushX_Axis_L.setObjectName(_fromUtf8("pushX_Axis_L"))
        self.gridLayout_4.addWidget(self.pushX_Axis_L, 2, 2, 1, 1)
        self.label_52 = QtGui.QLabel(self.groupBox_10)
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.gridLayout_4.addWidget(self.label_52, 3, 0, 1, 1)
        spacerItem19 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem19, 3, 1, 1, 1)
        self.pushX_Axis_R = InputButton(self.groupBox_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushX_Axis_R.sizePolicy().hasHeightForWidth())
        self.pushX_Axis_R.setSizePolicy(sizePolicy)
        self.pushX_Axis_R.setAutoDefault(False)
        self.pushX_Axis_R.setObjectName(_fromUtf8("pushX_Axis_R"))
        self.gridLayout_4.addWidget(self.pushX_Axis_R, 3, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_4)
        self.gridLayout_8.addWidget(self.groupBox_10, 2, 0, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_7 = QtGui.QLabel(self.groupBox_5)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_6.addWidget(self.label_7, 0, 0, 1, 1)
        spacerItem20 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem20, 0, 1, 1, 1)
        self.pushB_Button = InputButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushB_Button.sizePolicy().hasHeightForWidth())
        self.pushB_Button.setSizePolicy(sizePolicy)
        self.pushB_Button.setAutoDefault(False)
        self.pushB_Button.setObjectName(_fromUtf8("pushB_Button"))
        self.gridLayout_6.addWidget(self.pushB_Button, 0, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_5)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_6.addWidget(self.label_8, 1, 0, 1, 1)
        spacerItem21 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem21, 1, 1, 1, 1)
        self.pushA_Button = InputButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushA_Button.sizePolicy().hasHeightForWidth())
        self.pushA_Button.setSizePolicy(sizePolicy)
        self.pushA_Button.setAutoDefault(False)
        self.pushA_Button.setObjectName(_fromUtf8("pushA_Button"))
        self.gridLayout_6.addWidget(self.pushA_Button, 1, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_5)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_6.addWidget(self.label_9, 2, 0, 1, 1)
        spacerItem22 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem22, 2, 1, 1, 1)
        self.pushMempak = InputButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushMempak.sizePolicy().hasHeightForWidth())
        self.pushMempak.setSizePolicy(sizePolicy)
        self.pushMempak.setAutoDefault(False)
        self.pushMempak.setObjectName(_fromUtf8("pushMempak"))
        self.gridLayout_6.addWidget(self.pushMempak, 2, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox_5)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_6.addWidget(self.label_10, 3, 0, 1, 1)
        spacerItem23 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem23, 3, 1, 1, 1)
        self.pushRumblepak = InputButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushRumblepak.sizePolicy().hasHeightForWidth())
        self.pushRumblepak.setSizePolicy(sizePolicy)
        self.pushRumblepak.setAutoDefault(False)
        self.pushRumblepak.setObjectName(_fromUtf8("pushRumblepak"))
        self.gridLayout_6.addWidget(self.pushRumblepak, 3, 2, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_6)
        self.gridLayout_8.addWidget(self.groupBox_5, 2, 2, 1, 1)
        spacerItem24 = QtGui.QSpacerItem(178, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem24, 3, 0, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushStart = InputButton(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pushStart.sizePolicy().hasHeightForWidth())
        self.pushStart.setSizePolicy(sizePolicy)
        self.pushStart.setMinimumSize(QtCore.QSize(0, 0))
        self.pushStart.setAutoDefault(False)
        self.pushStart.setObjectName(_fromUtf8("pushStart"))
        self.horizontalLayout_2.addWidget(self.pushStart)
        self.label_5 = QtGui.QLabel(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_2.addWidget(self.label_5)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_2)
        spacerItem25 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem25)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_6 = QtGui.QLabel(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_3.addWidget(self.label_6)
        self.pushZ_Trig = InputButton(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pushZ_Trig.sizePolicy().hasHeightForWidth())
        self.pushZ_Trig.setSizePolicy(sizePolicy)
        self.pushZ_Trig.setAutoDefault(False)
        self.pushZ_Trig.setObjectName(_fromUtf8("pushZ_Trig"))
        self.horizontalLayout_3.addWidget(self.pushZ_Trig)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_3)
        self.gridLayout_8.addLayout(self.horizontalLayout_8, 3, 1, 1, 1)
        spacerItem26 = QtGui.QSpacerItem(208, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem26, 3, 2, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_8)
        self.verticalLayout_6.addWidget(self.groupBox_6)
        self.verticalLayout_8.addWidget(self.groupBox)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.statusLabel = QtGui.QLabel(InputDialog)
        self.statusLabel.setText(_fromUtf8(""))
        self.statusLabel.setObjectName(_fromUtf8("statusLabel"))
        self.horizontalLayout.addWidget(self.statusLabel)
        spacerItem27 = QtGui.QSpacerItem(288, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem27)
        self.pushButton = QtGui.QPushButton(InputDialog)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout_8.addLayout(self.horizontalLayout)
        self.label.setBuddy(self.comboDevice)
        self.label_2.setBuddy(self.comboPlugin)

        self.retranslateUi(InputDialog)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), InputDialog.close)
        QtCore.QMetaObject.connectSlotsByName(InputDialog)

    def retranslateUi(self, InputDialog):
        self.groupBox.setTitle(QtGui.QApplication.translate("InputDialog", "Input-SDL-Control", None, QtGui.QApplication.UnicodeUTF8))
        self.checkPlugged.setText(QtGui.QApplication.translate("InputDialog", "Plugged", None, QtGui.QApplication.UnicodeUTF8))
        self.checkMouse.setText(QtGui.QApplication.translate("InputDialog", "Mouse", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("InputDialog", "Device", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("InputDialog", "Plugin", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("InputDialog", "AnalogDeadzone", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("InputDialog", "X:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("InputDialog", "Y:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("InputDialog", "AnalogPeak", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("InputDialog", "X:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("InputDialog", "Y:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushL_Trig.setText(QtGui.QApplication.translate("InputDialog", "Select...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("InputDialog", "L Trigger", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("InputDialog", "R Trigger", None, QtGui.QApplication.UnicodeUTF8))
        self.pushR_Trig.setText(QtGui.QApplication.translate("InputDialog", "Select...", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("InputDialog", "Digital Pad", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("InputDialog", "Up", None, QtGui.QApplication.UnicodeUTF8))
        self.pushDPad_U.setText(QtGui.QApplication.translate("InputDialog", "Select...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("InputDialog", "Down", None, QtGui.QApplication.UnicodeUTF8))
        self.pushDPad_D.setText(QtGui.QApplication.translate("InputDialog", "Select...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("InputDialog", "Left", None, QtGui.QApplication.UnicodeUTF8))
        self.pushDPad_L.setText(QtGui.QApplication.translate("InputDialog", "Select...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("InputDialog", "Right", None, QtGui.QApplication.UnicodeUTF8))
        self.pushDPad_R.setText(QtGui.QApplication.translate("InputDialog", "Select...", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_9.setTitle(QtGui.QApplication.translate("InputDialog", "C - Buttons", None, QtGui.QApplication.UnicodeUTF8))
        self.pushC_Button_U.setText(QtGui.QApplication.translate("InputDialog", "Select...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_47.setText(QtGui.QApplication.translate("InputDialog", "Left", None, QtGui.QApplication.UnicodeUTF8))
        self.pushC_Button_R.setText(QtGui.QApplication.translate("InputDialog", "Select...", None, QtGui.QApplication.UnicodeUTF8))
        self.pushC_Button_L.setText(QtGui.QApplication.translate("InputDialog", "Select...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_48.setText(QtGui.QApplication.translate("InputDialog", "Right", None, QtGui.QApplication.UnicodeUTF8))
        self.label_45.setText(QtGui.QApplication.translate("InputDialog", "Up", None, QtGui.QApplication.UnicodeUTF8))
        self.pushC_Button_D.setText(QtGui.QApplication.translate("InputDialog", "Select...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_46.setText(QtGui.QApplication.translate("InputDialog", "Down", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_10.setTitle(QtGui.QApplication.translate("InputDialog", "Analog Stick", None, QtGui.QApplication.UnicodeUTF8))
        self.label_50.setText(QtGui.QApplication.translate("InputDialog", "Up", None, QtGui.QApplication.UnicodeUTF8))
        self.pushY_Axis_U.setText(QtGui.QApplication.translate("InputDialog", "Select...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_51.setText(QtGui.QApplication.translate("InputDialog", "Down", None, QtGui.QApplication.UnicodeUTF8))
        self.pushY_Axis_D.setText(QtGui.QApplication.translate("InputDialog", "Select...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_49.setText(QtGui.QApplication.translate("InputDialog", "Left", None, QtGui.QApplication.UnicodeUTF8))
        self.pushX_Axis_L.setText(QtGui.QApplication.translate("InputDialog", "Select...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_52.setText(QtGui.QApplication.translate("InputDialog", "Right", None, QtGui.QApplication.UnicodeUTF8))
        self.pushX_Axis_R.setText(QtGui.QApplication.translate("InputDialog", "Select...", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("InputDialog", "Buttons", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("InputDialog", "B Button", None, QtGui.QApplication.UnicodeUTF8))
        self.pushB_Button.setText(QtGui.QApplication.translate("InputDialog", "Select...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("InputDialog", "A Button", None, QtGui.QApplication.UnicodeUTF8))
        self.pushA_Button.setText(QtGui.QApplication.translate("InputDialog", "Select...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("InputDialog", "Mempak", None, QtGui.QApplication.UnicodeUTF8))
        self.pushMempak.setText(QtGui.QApplication.translate("InputDialog", "Select...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("InputDialog", "Rumblepak", None, QtGui.QApplication.UnicodeUTF8))
        self.pushRumblepak.setText(QtGui.QApplication.translate("InputDialog", "Select...", None, QtGui.QApplication.UnicodeUTF8))
        self.pushStart.setText(QtGui.QApplication.translate("InputDialog", "Select...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("InputDialog", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("InputDialog", "Z Trigger", None, QtGui.QApplication.UnicodeUTF8))
        self.pushZ_Trig.setText(QtGui.QApplication.translate("InputDialog", "Select...", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("InputDialog", "&Close", None, QtGui.QApplication.UnicodeUTF8))

from inputbutton import InputButton
import images_rc
